[build]
  functions = ".netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

# Redirect rules for GitHub OAuth callback
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

# API routes
[[redirects]]
  from = "/api/github-oauth"
  to = "/.netlify/functions/github-oauth"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORS headers for API endpoints  
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"