# Nixpacks configuration for FlowDesk
[phases.build]
cmds = [
  "cd backend",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/backend"
NIXPACKS_PYTHON_VERSION = "3.11"