# Nixpacks configuration for FlowDesk
[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONPATH = "/app/backend"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build complete'"

[phases.start]
cmd = "./start.sh"